### ISSUE TITLE
Licence header

### ISSUE THREAD

**Issue by jlaine** [mourner/kdbush.hpp#6]
Hi Vladimir,

I am currently playing with a python wrapper around kdbush.hpp, and so far the results look promising. One minor issue I have is that it means embedding kdbush.hpp, which currently has no copyright / licence header. Would you consider adding it?

Thanks!
Jeremy

**Comment by mourner** [comment]
If you need a header, you can include the contents of [LICENSE](https://github.com/mourner/kdbush.hpp/blob/master/LICENSE) in your wrapper, or alongside kdbush.hpp. I don't think it's needed in the header explicitly in this repo.

**Comment by jlaine** [comment]
Thanks I have done as suggested, see:

https://github.com/wemap/pysupercluster
